package com.oop.bibtex.main;

public enum Attributes {
    AUTHOR, TITLE, JOURNAL, YEAR, VOLUME, NUMBER, PAGES, MONTH,NOTE, KEY, PUBLISHER, SERIES, ADDRESS, EDITION,
    BOOKTITLE, ORGANIZATION, HOWPUBLISHED, CHAPTER, SCHOOL, INSTITUTION, ISBN
}
